config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'bank_accounts/show'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :bank_accounts, only: [:show]

  namespace :api do
    namespace :v1 do
      post "transactions/new", to: "transactions#new"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord

  belongs_to :user
  has_many :transactions

  # validates :user, presence: true
  validates :balance, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :account_number, presence: true, uniqueness: true

  before_validation :load_defaults

  def load_defaults
    return unless new_record?

    self.balance = 0.00 unless balance.present?
    self.account_number = SecureRandom.uuid unless account_number.present?
  end

  def to_s
    account_number
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :bank_account

  TRANSACTION_TYPES = %w[withdraw deposit transfer].freeze

  validates :bank_account, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPES }
  validates :transaction_number, presence: true, uniqueness: true
  validates :recipient_id, presence: true

  before_validation :load_defaults

  def load_defaults
    self.transaction_number = SecureRandom.uuid if new_record? && !transaction_number.present?
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_one :bank_account

  has_secure_password

  validates :name,  presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }



  validates :password, presence: true, length: { minimum: 8 }

  after_create :add_bank_account

  def add_bank_account
    create_bank_account
  end

  def to_s
    name
  end

  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end

    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/api/v1/transactions_controller.rb
module Api
  module V1
    class TransactionsController < ApplicationController
      def new
        errors = Transactions::Validate.new(
          amount: params[:amount],
          transaction_type: params[:transaction_type],
          bank_account_id: params[:bank_account_id],
          recipient_id: params[:recipient_id]).execute!
        if errors.size > 0
          render json: { errors: errors }, status: 402
        else
          bank_account = Transactions::Perform.new(
            amount: params[:amount],
            transaction_type: params[:transaction_type],
            bank_account_id: params[:bank_account_id],
            recipient_id: params[:recipient_id]).execute!
          render json: { balance: bank_account.balance }
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  def show
    @bank_account = BankAccount.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to the Banking App! Your account has been created'
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/bank_accounts/_modal_transaction.html.haml
#modal-transaction.modal.fade.modal-fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type:'button', data:{dismiss:'modal'}}
          %span{aria:{hidden:'true'}}
            %i.fa.fa-close
          %span.sr-only Close
        %h4.modal-title
          New Transaction
      .modal-body
        .row
          .col-md-12
            .notification
        .row
          .col-md-4
            %label
              Amount
            = text_field_tag :amount, 0.00, id: "input-amount", class: "form-control"
          .col-md-4
            %label
              Transaction Type
            = select_tag :transaction_type, options_for_select(Transaction::TRANSACTION_TYPES), id: "select-transaction-type", class: "form-control"
          .col-md-4
            %label
              Recipient Account Number
            = text_field_tag :recipient_id, @bank_account.account_number,id: "input-recipient", class: "form-control"
      .modal-footer
        %button.btn.btn-default{type:'button', data:{dismiss:'modal'}} Close
        %button#btn-save.btn.btn-primary{type:'button'} Save

app/views/bank_accounts/_transactions.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Date of Transaction
      %th Transaction Type
      %th Recipient
      %th Amount
  %tbody
    - bank_account.transactions.each do |t|
      %tr
        %td #{t.created_at}
        %td #{t.transaction_type}
        %td #{t.recipient_id}
        %td #{number_to_currency(t.amount, unit: "₹")}
    %tr
      %th
      %th
      %th Balance
      %th #{number_to_currency(bank_account.balance, unit: "₹")}

app/views/bank_accounts/show.html.haml
%h1
  Account Number: #{@bank_account.account_number}
  %small
    #{@bank_account.user}

= button_tag :new_transaction, id: "btn-new-transaction", class: "btn btn-primary" do
  New Transaction

= render partial: "transactions", locals: { bank_account: @bank_account }

#parameters{data: {bank_account_id: @bank_account.id, bank_account_number: @bank_account.account_number}}

= render partial: "modal_transaction"

= javascript_include_tag "bank_accounts/Show"
:javascript
  $(document).ready(function() {
      Show.init();
  });

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    This site is developed by Yedukondala Reddy

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "Banking App", root_path , id: "logo"
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Home", root_path
          - if logged_in?
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li
                  = link_to "Log out", logout_path, method: :delete
          - else
            %li= link_to "Log in", login_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BankRailsApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{class: "alert alert-#{message_type}"}= message
      = yield
      = render 'layouts/footer'

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(@user.errors.count, "error")}.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

app/views/static_pages/home.html.haml
.center.jumbotron
  %h1 Welcome to the Bank App
  %h2
    Sign Up to create your Bank account
  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign up
.row
  .col-md-6.col-md-offset-3
    = form_for(@user, url: signup_path) do |f|
      = render 'shared/error_messages'
      = f.label :name
      = f.text_field :name, class: 'form-control'
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :password
      = f.password_field :password, class: 'form-control'
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.name)
.row
  %aside.col-md-4
    %section.user_info
      %h1
        = gravatar_for @user
        = @user.name
.row
  .col-md-12
    = link_to "Account Details", bank_account_path(@user&.bank_account&.id), class: "btn btn-lg btn-primary"